// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/customerTicket": {
            "post": {
                "description": "endpoint CustomerTicket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomerTicket"
                ],
                "summary": "API Create CustomerTicket",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Request Parameters",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/customerTicketModel.CreateCustomerTicket"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/customerTicket/list": {
            "get": {
                "description": "endpoint CustomerTicket list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomerTicket"
                ],
                "summary": "API List CustomerTicket",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/customerTicketModel.CustomerTicketList"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/customerTicketModel.CustomerTicketList"
                        }
                    }
                }
            }
        },
        "/customerTicket/{id}/delete": {
            "delete": {
                "description": "endpoint CustomerTicket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomerTicket"
                ],
                "summary": "API Delete CustomerTicket",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "CustomerTicket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/customerTicket/{id}/detail": {
            "get": {
                "description": "endpoint CustomerTicket detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomerTicket"
                ],
                "summary": "API Detail CustomerTicket",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "CustomerTicket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/customerTicketModel.CustomerTicket"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/customerTicketModel.CustomerTicket"
                        }
                    }
                }
            }
        },
        "/customerTicket/{id}/update": {
            "put": {
                "description": "endpoint CustomerTicket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CustomerTicket"
                ],
                "summary": "API Update CustomerTicket",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "CustomerTicket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request Parameters",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/customerTicketModel.UpdateCustomerTicket"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/discount": {
            "post": {
                "description": "endpoint Discount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount"
                ],
                "summary": "API Create Discount",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Request Parameters",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/discountModel.CreateDiscount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/discount/list": {
            "get": {
                "description": "endpoint Discount list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount"
                ],
                "summary": "API List Discount",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/discountModel.DiscountList"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/discountModel.DiscountList"
                        }
                    }
                }
            }
        },
        "/discount/{id}/delete": {
            "delete": {
                "description": "endpoint Discount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount"
                ],
                "summary": "API Delete Discount",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "Discount ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/discount/{id}/detail": {
            "get": {
                "description": "endpoint Discount detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount"
                ],
                "summary": "API Detail Discount",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "Discount ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/discountModel.Discount"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/discountModel.Discount"
                        }
                    }
                }
            }
        },
        "/discount/{id}/update": {
            "put": {
                "description": "endpoint Discount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Discount"
                ],
                "summary": "API Update Discount",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "Discount ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request Parameters",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/discountModel.UpdateDiscount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/health-check": {
            "get": {
                "description": "endpoint HealthCheck list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HealthCheck"
                ],
                "summary": "API List HealthCheck",
                "responses": {}
            }
        },
        "/stockType": {
            "post": {
                "description": "endpoint StockType",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StockType"
                ],
                "summary": "API Create StockType",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Request Parameters",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/stockTypeModel.CreateStockType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/stockType/list": {
            "get": {
                "description": "endpoint StockType list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StockType"
                ],
                "summary": "API List StockType",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/stockTypeModel.StockTypeList"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/stockTypeModel.StockTypeList"
                        }
                    }
                }
            }
        },
        "/stockType/{id}/delete": {
            "delete": {
                "description": "endpoint StockType",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StockType"
                ],
                "summary": "API Delete StockType",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "StockType ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/stockType/{id}/detail": {
            "get": {
                "description": "endpoint StockType detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StockType"
                ],
                "summary": "API Detail StockType",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "StockType ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/stockTypeModel.StockType"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/stockTypeModel.StockType"
                        }
                    }
                }
            }
        },
        "/stockType/{id}/update": {
            "put": {
                "description": "endpoint StockType",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StockType"
                ],
                "summary": "API Update StockType",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "StockType ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request Parameters",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/stockTypeModel.UpdateStockType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/ticket": {
            "post": {
                "description": "endpoint Ticket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "API Create Ticket",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Request Parameters",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ticketModel.CreateTicket"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/ticket/list": {
            "get": {
                "description": "endpoint Ticket list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "API List Ticket",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/ticketModel.TicketList"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/ticketModel.TicketList"
                        }
                    }
                }
            }
        },
        "/ticket/{id}/delete": {
            "delete": {
                "description": "endpoint Ticket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "API Delete Ticket",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/ticket/{id}/detail": {
            "get": {
                "description": "endpoint Ticket detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "API Detail Ticket",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/ticketModel.Ticket"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/ticketModel.Ticket"
                        }
                    }
                }
            }
        },
        "/ticket/{id}/update": {
            "put": {
                "description": "endpoint Ticket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "API Update Ticket",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request Parameters",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ticketModel.UpdateTicket"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/ticketCategory": {
            "post": {
                "description": "endpoint Ticket Category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket Category"
                ],
                "summary": "API Create Ticket Category",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Request Parameters",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ticketCategoryModel.TicketCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/ticketCategory/list": {
            "get": {
                "description": "endpoint Ticket Category list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket Category"
                ],
                "summary": "API List Ticket Category",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/ticketCategoryModel.TicketCategoryList"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/ticketCategoryModel.TicketCategoryList"
                        }
                    }
                }
            }
        },
        "/ticketCategory/{id}/delete": {
            "delete": {
                "description": "endpoint Ticket Category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket Category"
                ],
                "summary": "API Delete Ticket Category",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "TicketCategory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/ticketCategory/{id}/detail": {
            "get": {
                "description": "endpoint Ticket Category detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket Category"
                ],
                "summary": "API Detail Ticket Category",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "TicketCategory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/ticketCategoryModel.TicketCategory"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/ticketCategoryModel.TicketCategory"
                        }
                    }
                }
            }
        },
        "/ticketCategory/{id}/update": {
            "put": {
                "description": "endpoint Ticket Category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket Category"
                ],
                "summary": "API Update Ticket Category",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "TicketCategory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request Parameters",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ticketCategoryModel.TicketCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "customerTicketModel.CreateCustomerTicket": {
            "type": "object",
            "required": [
                "code",
                "customer_id",
                "ticket_id",
                "transaction_id",
                "used_at",
                "valid_at",
                "valid_until"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "integer"
                },
                "ticket_id": {
                    "type": "integer"
                },
                "transaction_id": {
                    "type": "integer"
                },
                "used_at": {
                    "type": "string"
                },
                "valid_at": {
                    "type": "string"
                },
                "valid_until": {
                    "type": "string"
                }
            }
        },
        "customerTicketModel.CustomerTicket": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "integer"
                },
                "deleted_at": {
                    "type": "string"
                },
                "deleted_by": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ticket_id": {
                    "type": "integer"
                },
                "transaction_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                },
                "used_at": {
                    "type": "string"
                },
                "valid_at": {
                    "type": "string"
                },
                "valid_until": {
                    "type": "string"
                }
            }
        },
        "customerTicketModel.CustomerTicketEntity": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "ticket": {
                    "$ref": "#/definitions/customerTicketModel.Ticket"
                },
                "ticket_id": {
                    "type": "integer"
                },
                "transaction_id": {
                    "type": "integer"
                },
                "used_at": {
                    "type": "string"
                },
                "valid_at": {
                    "type": "string"
                },
                "valid_until": {
                    "type": "string"
                }
            }
        },
        "customerTicketModel.CustomerTicketList": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/customerTicketModel.CustomerTicketEntity"
                    }
                },
                "sort": {
                    "type": "string"
                },
                "total_pages": {
                    "type": "integer"
                },
                "total_rows": {
                    "type": "integer"
                }
            }
        },
        "customerTicketModel.Ticket": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "item_code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "customerTicketModel.UpdateCustomerTicket": {
            "type": "object",
            "required": [
                "code",
                "customer_id",
                "ticket_id",
                "transaction_id",
                "used_at",
                "valid_at",
                "valid_until"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "integer"
                },
                "ticket_id": {
                    "type": "integer"
                },
                "transaction_id": {
                    "type": "integer"
                },
                "used_at": {
                    "type": "string"
                },
                "valid_at": {
                    "type": "string"
                },
                "valid_until": {
                    "type": "string"
                }
            }
        },
        "discountModel.CreateDiscount": {
            "type": "object",
            "required": [
                "discount_type",
                "discount_value",
                "is_active",
                "name"
            ],
            "properties": {
                "discount_type": {
                    "$ref": "#/definitions/discountModel.DiscountType"
                },
                "discount_value": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "discountModel.Discount": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "deleted_by": {
                    "type": "string"
                },
                "discount_type": {
                    "$ref": "#/definitions/discountModel.DiscountType"
                },
                "discount_value": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "discountModel.DiscountList": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/discountModel.Discount"
                    }
                },
                "sort": {
                    "type": "string"
                },
                "total_pages": {
                    "type": "integer"
                },
                "total_rows": {
                    "type": "integer"
                }
            }
        },
        "discountModel.DiscountType": {
            "type": "string",
            "enum": [
                "P",
                "A"
            ],
            "x-enum-varnames": [
                "P",
                "A"
            ]
        },
        "discountModel.UpdateDiscount": {
            "type": "object",
            "required": [
                "discount_type",
                "discount_value",
                "is_active",
                "name"
            ],
            "properties": {
                "discount_type": {
                    "$ref": "#/definitions/discountModel.DiscountType"
                },
                "discount_value": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "helperModel.BaseResponseModel": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "stockTypeModel.CreateStockType": {
            "type": "object",
            "required": [
                "description",
                "is_active",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "stockTypeModel.StockType": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "deleted_by": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "stockTypeModel.StockTypeList": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/stockTypeModel.StockType"
                    }
                },
                "sort": {
                    "type": "string"
                },
                "total_pages": {
                    "type": "integer"
                },
                "total_rows": {
                    "type": "integer"
                }
            }
        },
        "stockTypeModel.UpdateStockType": {
            "type": "object",
            "required": [
                "description",
                "is_active",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "ticketCategoryModel.TicketCategory": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "deleted_by": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "ticketCategoryModel.TicketCategoryList": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ticketCategoryModel.TicketCategory"
                    }
                },
                "sort": {
                    "type": "string"
                },
                "total_pages": {
                    "type": "integer"
                },
                "total_rows": {
                    "type": "integer"
                }
            }
        },
        "ticketCategoryModel.TicketCategoryRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "ticketModel.CreateTicket": {
            "type": "object",
            "required": [
                "available_date",
                "default_discount",
                "default_price",
                "description",
                "discount_id",
                "is_active",
                "is_using_stock",
                "item_code",
                "item_content_id",
                "name",
                "stock",
                "stock_type_id",
                "ticket_category_id"
            ],
            "properties": {
                "available_date": {
                    "type": "string",
                    "example": "2024-01-24"
                },
                "default_discount": {
                    "type": "integer"
                },
                "default_price": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "discount_id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_using_stock": {
                    "type": "boolean"
                },
                "item_code": {
                    "type": "string",
                    "example": "P-240005"
                },
                "item_content_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                },
                "stock_type_id": {
                    "type": "integer"
                },
                "ticket_category_id": {
                    "type": "integer"
                }
            }
        },
        "ticketModel.Discount": {
            "type": "object",
            "properties": {
                "discount_type": {
                    "type": "string"
                },
                "discount_value": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "ticketModel.StockType": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "ticketModel.Ticket": {
            "type": "object",
            "properties": {
                "available_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "default_discount": {
                    "type": "integer"
                },
                "default_price": {
                    "type": "integer"
                },
                "deleted_at": {
                    "type": "string"
                },
                "deleted_by": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "discount_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_using_stock": {
                    "type": "boolean"
                },
                "item_code": {
                    "type": "string"
                },
                "item_content_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                },
                "stock_type_id": {
                    "type": "integer"
                },
                "ticket_category_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "ticketModel.TicketEntity": {
            "type": "object",
            "properties": {
                "available_date": {
                    "type": "string"
                },
                "default_discount": {
                    "type": "integer"
                },
                "default_price": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "discount": {
                    "$ref": "#/definitions/ticketModel.Discount"
                },
                "discount_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_using_stock": {
                    "type": "boolean"
                },
                "item_code": {
                    "type": "string"
                },
                "item_content_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                },
                "stock_type": {
                    "$ref": "#/definitions/ticketModel.StockType"
                },
                "stock_type_id": {
                    "type": "integer"
                }
            }
        },
        "ticketModel.TicketList": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ticketModel.TicketEntity"
                    }
                },
                "sort": {
                    "type": "string"
                },
                "total_pages": {
                    "type": "integer"
                },
                "total_rows": {
                    "type": "integer"
                }
            }
        },
        "ticketModel.UpdateTicket": {
            "type": "object",
            "required": [
                "available_date",
                "default_discount",
                "default_price",
                "description",
                "discount_id",
                "is_active",
                "is_using_stock",
                "item_code",
                "item_content_id",
                "name",
                "stock",
                "stock_type_id",
                "ticket_category_id"
            ],
            "properties": {
                "available_date": {
                    "type": "string",
                    "example": "2024-01-24"
                },
                "default_discount": {
                    "type": "integer"
                },
                "default_price": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "discount_id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_using_stock": {
                    "type": "boolean"
                },
                "item_code": {
                    "type": "string",
                    "example": "P-240005"
                },
                "item_content_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                },
                "stock_type_id": {
                    "type": "integer"
                },
                "ticket_category_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Service Ticket - Bali Xperience Swagger API Documentation",
	Description:      "This is API Documentation for Service Ticket - Bali Xperience Swagger Services.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
