// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health-check": {
            "get": {
                "description": "LOV untuk health check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HealthCheck"
                ],
                "summary": "Get Health Check",
                "responses": {}
            }
        },
        "/product": {
            "post": {
                "description": "endpoint create Product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "API create Product",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Request Parameters",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/productModel.ProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/product/list": {
            "get": {
                "description": "endpoint Product list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "API List Product",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/productModel.ProductListResponse"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/product/{id}/delete": {
            "delete": {
                "description": "endpoint delete Product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "API delete Product",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "example": "1",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/product/{id}/detail": {
            "get": {
                "description": "endpoint detail Product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "API Detail Product",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "example": "1",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/productModel.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/product/{id}/update": {
            "put": {
                "description": "endpoint Update Product",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "API Update Product",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiNWQxNjY5NS0xZjJlLTQ1...",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "example": "1",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request Parameters",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/productModel.ProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    },
                    "400": {
                        "description": "Response Error",
                        "schema": {
                            "$ref": "#/definitions/helperModel.BaseResponseModel"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Login For User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "API Login User",
                "parameters": [
                    {
                        "description": "Request Parameters",
                        "name": "LoginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userModel.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/userModel.CreateUserResponse"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Create For User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "API Create User",
                "parameters": [
                    {
                        "description": "Request Parameters",
                        "name": "CreateUserRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userModel.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/userModel.CreateUserResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "helperModel.BaseResponseModel": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "productModel.Product": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "product_code": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                }
            }
        },
        "productModel.ProductListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/productModel.Product"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "productModel.ProductRequest": {
            "type": "object",
            "required": [
                "product_code",
                "product_name"
            ],
            "properties": {
                "product_code": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                }
            }
        },
        "productModel.ProductResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/productModel.Product"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "userModel.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "phone_number"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "userModel.CreateUserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "kode_user": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "userModel.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Product Service API Documentation",
	Description:      "This is API Documentation for Product Service Services.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
