basePath: /api/v1
definitions:
  userModel.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone_number:
        type: string
    required:
    - email
    - name
    - password
    - phone_number
    type: object
  userModel.CreateUserResponse:
    properties:
      email:
        type: string
      name:
        type: string
      phone_number:
        type: string
    type: object
  userModel.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is API Documentation for Product Service Services.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Product Service API Documentation
  version: "2.0"
paths:
  /health-check:
    get:
      consumes:
      - application/json
      description: LOV untuk health check
      produces:
      - application/json
      responses: {}
      summary: Get Health Check
      tags:
      - HealthCheck
  /user/login:
    post:
      consumes:
      - application/json
      description: Login For User
      parameters:
      - description: Request Parameters
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/userModel.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Response Success
          schema:
            $ref: '#/definitions/userModel.CreateUserResponse'
      summary: API Login User
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      description: Create For User
      parameters:
      - description: Request Parameters
        in: body
        name: CreateUserRequest
        required: true
        schema:
          $ref: '#/definitions/userModel.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Response Success
          schema:
            $ref: '#/definitions/userModel.CreateUserResponse'
      summary: API Create User
      tags:
      - User
schemes:
- http
- https
swagger: "2.0"
